/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': '#0b1326',
        'inverse-on-surface': '#283044',
        'on-background': '#dae2fd',
        'on-secondary-fixed': '#140f54',
        'inverse-surface': '#dae2fd',
        'on-secondary-container': '#b0aef9',
        'primary-fixed-dim': '#c3c0ff',
        'primary-container': '#4f46e5',
        secondary: '#c3c0ff',
        'on-surface': '#dae2fd',
        'surface-container-high': '#222a3d',
        'on-tertiary-fixed-variant': '#653e00',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#e2dfff',
        background: '#0b1326',
        'tertiary-fixed': '#ffddb8',
        'error-container': '#93000a',
        'on-tertiary': '#472a00',
        'on-surface-variant': '#c7c4d8',
        'surface-container': '#171f33',
        error: '#ffb4ab',
        'on-error': '#690005',
        'surface-tint': '#c3c0ff',
        primary: '#c3c0ff',
        'secondary-container': '#413f82',
        'on-tertiary-fixed': '#2a1700',
        'on-primary-fixed': '#0f0069',
        'on-tertiary-container': '#ffd4a4',
        'surface-container-lowest': '#060e20',
        tertiary: '#ffb95f',
        'tertiary-container': '#885500',
        'surface-container-low': '#131b2e',
        'surface-variant': '#2d3449',
        'on-secondary': '#2a276a',
        'on-primary-fixed-variant': '#3323cc',
        'on-primary-container': '#dad7ff',
        'primary-fixed': '#e2dfff',
        'secondary-fixed-dim': '#c3c0ff',
        'surface-container-highest': '#2d3449',
        'inverse-primary': '#4d44e3',
        outline: '#918fa1',
        'surface-bright': '#31394d',
        'outline-variant': '#464555',
        'tertiary-fixed-dim': '#ffb95f',
        'on-secondary-fixed-variant': '#413f82',
        'on-primary': '#1d00a5',
        surface: '#0b1326',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        atmospheric: '0px 20px 40px rgba(6, 14, 32, 0.4)',
        'atmospheric-sm': '0px 12px 32px rgba(30, 27, 75, 0.06)',
      },
    },
  },
  plugins: [],
};
